name: CI

on: 
  push:
    branches: 
      - jeff-dev
env:
  createRatingAppName: azure-function-20200116125628847

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install maven and Java
      run: |
        sudo apt-get install openjdk-8-jre
        sudo apt-get install maven
    
    - name: Maven package createRating
      run: |
        cd ./ratingsAPIs/createRating
        mvn clean package
        
    - name: Upload artifact createRating
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: createRatingApp
        # Directory containing files to upload
        path: ./ratingsAPIs/createRating/target/azure-functions/${{ env.createRatingAppName }}
        
  release:
    needs: build
    runs-on: [ubuntu-latest]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          # Artifact name
          name: createRatingApp
          # Destination path
          path: ./artifacts/createRatingApp
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Functions Action
        uses: Azure/functions-action@v1.1.3
        with:
          # Name of the Azure Function App
          app-name: jeff-test-githubactions
          # Path to package or folder. *.zip or a folder to deploy
          package: ./artifacts/createRatingApp
        
    
